version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: Upgrade
      prefix-development: Build