rules:
  'type-enum':
    - 2
    - always
    - [
        'New',
        'Fix', 
        'Build',
        'Docs',
        'Upgrade',
        'Breaking',
        'Update'
      ]
  'type-case': [2, 'always', 'pascal-case']
  'type-empty': [2, 'never']
  'scope-case': [2, 'always', 'lower-case']
  'subject-empty': [2, 'never']
  'subject-full-stop': [2, 'never', '.']
  'header-max-length': [2, 'always', 72]
  'body-leading-blank': [2, 'always']
  'footer-leading-blank': [2, 'always']