// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240218a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 19.02.2024 00:10
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240218a) build in default

class IMissingImageFilesChecker
{
// Prolog Standard <----

    /**
     * <b>B01: image src is data uri</b>
     */
    isImageSrcIsDataUri(model) {
    }

    /**
     * <b>B02: image src is remote uri</b>
     */
    isImageSrcIsRemoteUri(model) {
    }

    /**
     * <b>B03: image src contains data</b>
     */
    isImageSrcContainsData(model) {
    }

    /**
     * <b>B04: local image file exists</b>
     */
    isLocalImageFileExists(model) {
    }

    /**
     * <b>A01: create finding</b><br>
     * <br>
     * <b>A01/01: DATA - data-uri image missing</b>
     */
    doCreateFinding_DATA(model) {
    }

    /**
     * <b>A01: create finding</b><br>
     * <br>
     * <b>A01/02: FILE - image\"$relativePathToImageFile\" missing</b>
     */
    doCreateFinding_FILE(model) {
    }

    /**
     * <b>A02: inc number of checks</b><br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=inc number of checks; CA=Text<br>
     * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
     */
    doIncNumberOfChecks(/* IncNumberOfChecks */ arg, model) {
    }
}

/**
 * <b>A02: inc number of checks</b><br>
 * <br>
 * <b>A02/01: +1 - one check</b>
 */
const IncNumberOfChecks_1 = new IncNumberOfChecks();

/**
 * <b>A02: inc number of checks</b><br>
 * <br>
 * <b>A02/02: 0 - 0 checks</b>
 */
const IncNumberOfChecks_0 = new IncNumberOfChecks();

/**
 * <b>A02: inc number of checks</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=inc number of checks; CA=Text<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class IncNumberOfChecks
{
}

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.3.0 (240218a) build in default

module.exports = {
    IMissingImageFilesChecker,
    IncNumberOfChecks_1,
    IncNumberOfChecks_0
}

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240218a), https://www.lohrfink.de/lfet
