// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240218a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 19.02.2024 00:13
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (240218a) build in default

// cav = condition and action values
const cav = require('./IMissingImageFilesChecker.js')

class MissingImageFilesCheckerDecisionLogic {
    execute(/* IMissingImageFilesChecker */ iface, model) {
    // Prolog Standard <----

        if (iface.isImageSrcIsDataUri(model)) {
            if (iface.isImageSrcContainsData(model)) {
                // Rule R01 ---->

                console.log(`MissingImageFilesChecker - 20240219.001352 - 1 / 5 - ${JSON.stringify(model)}`)

                iface.doIncNumberOfChecks(cav.IncNumberOfChecks_1, model) // +1 - one check

                console.log(`MissingImageFilesChecker - 20240219.001352 - 1 / 5 - ${JSON.stringify(model)}`)

                // Rule R01 <----
            } else {
                // Rule R02 ---->

                console.log(`MissingImageFilesChecker - 20240219.001352 - 2 / 5 - ${JSON.stringify(model)}`)

                iface.doCreateFinding_DATA(model)
                iface.doIncNumberOfChecks(cav.IncNumberOfChecks_1, model) // +1 - one check

                console.log(`MissingImageFilesChecker - 20240219.001352 - 2 / 5 - ${JSON.stringify(model)}`)

                // Rule R02 <----
            }
        } else {
            if (iface.isImageSrcIsRemoteUri(model)) {
                // Rule R03 ---->

                console.log(`MissingImageFilesChecker - 20240219.001352 - 3 / 5 - ${JSON.stringify(model)}`)

                iface.doIncNumberOfChecks(cav.IncNumberOfChecks_0, model) // 0 - 0 checks

                console.log(`MissingImageFilesChecker - 20240219.001352 - 3 / 5 - ${JSON.stringify(model)}`)

                // Rule R03 <----
            } else {
                if (iface.isLocalImageFileExists(model)) {
                    // Rule R04 ---->

                    console.log(`MissingImageFilesChecker - 20240219.001352 - 4 / 5 - ${JSON.stringify(model)}`)

                    iface.doIncNumberOfChecks(cav.IncNumberOfChecks_1, model) // +1 - one check

                    console.log(`MissingImageFilesChecker - 20240219.001352 - 4 / 5 - ${JSON.stringify(model)}`)

                    // Rule R04 <----
                } else {
                    // Rule R05 ---->

                    console.log(`MissingImageFilesChecker - 20240219.001352 - 5 / 5 - ${JSON.stringify(model)}`)

                    iface.doCreateFinding_FILE(model)
                    iface.doIncNumberOfChecks(cav.IncNumberOfChecks_1, model) // +1 - one check

                    console.log(`MissingImageFilesChecker - 20240219.001352 - 5 / 5 - ${JSON.stringify(model)}`)

                    // Rule R05 <----
                }
            }
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (240218a) build in default

    }

}

module.exports = MissingImageFilesCheckerDecisionLogic

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240218a), https://www.lohrfink.de/lfet
