name: Dependabot auto-label
on: pull_request

permissions:
  pull-requests: write
  issues: write

jobs:
  get-metadata:
    uses: ./.github/workflows/dependabot-metadata.yml

  dependabot:
    runs-on: ubuntu-latest
    needs: get-metadata
    steps:
      - name: Add a label for all production dependencies
        if: needs.get-metadata.outputs.dependency-type == 'direct:production'
        run: gh pr edit "$PR_URL" --add-label "dep:production"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add a label for all development dependencies
        if: needs.get-metadata.outputs.dependency-type == 'direct:development'
        run: gh pr edit "$PR_URL" --add-label "dep:development"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add a label for all indirect dependencies
        if: needs.get-metadata.outputs.dependency-type == 'indirect'
        run: gh pr edit "$PR_URL" --add-label "dep:indirect"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}