// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240629a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/BrokenHttpLinksChecker.lfet"
// 03.07.2024 11:38
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240629a) build in default

class IBrokenHttpLinksChecker {
  // Prolog Standard <----

  /**
   * <b>B02: ignore localhost check</b><br>
   * <br>
   * <b>B02/01: Y - Yes</b>
   */
  isIgnoreLocalhostCheck (model) {
  }

  /**
   * <b>B03: check if localhost</b><br>
   * <br>
   * The enum generation has been triggered in project.ini by:<br>
   * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=check if localhost, create finding; Symbol; Title<br>
   * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
   */
  isCheckIfLocalhost (/* CheckIfLocalhost */ arg, model) {
  }

  /**
   * <b>B04: ignore ip address check</b><br>
   * <br>
   * <b>B04/01: Y - Yes</b>
   */
  isIgnoreIpAddressCheck (model) {
  }

  /**
   * <b>B05: check if ip address</b><br>
   * <br>
   * <b>B05/01: Y - Yes</b>
   */
  isCheckIfIpAddress (model) {
  }

  /**
   * <b>B06: check HEAD http status code in configured success range</b><br>
   * <br>
   * <b>B06/01: SUCCESS - configured success status code range</b>
   */
  isCheckHEADHttpStatusCodeInConfiguredSuccessRange_SUCCESS (model) {
  }

  /**
   * <b>B07: check HEAD http status code in redirect range</b><br>
   * <br>
   * <b>B07/01: 30x - [301:308]</b>
   */
  isCheckHEADHttpStatusCodeInRedirectRange_30X (model) {
  }

  /**
   * <b>B08: check GET http status code in configured ranges</b><br>
   * <br>
   * <b>B08/01: SUCCESS - success status range</b>
   */
  isCheckGETHttpStatusCodeInConfiguredRanges_SUCCESS (model) {
  }

  /**
   * <b>B08: check GET http status code in configured ranges</b><br>
   * <br>
   * <b>B08/02: WARN - warn status range</b>
   */
  isCheckGETHttpStatusCodeInConfiguredRanges_WARN (model) {
  }

  /**
   * <b>B08: check GET http status code in configured ranges</b><br>
   * <br>
   * <b>B08/03: ERROR - error status range</b>
   */
  isCheckGETHttpStatusCodeInConfiguredRanges_ERROR (model) {
  }

  /**
   * <b>B09: check if header contains location</b><br>
   * <br>
   * <b>B09/01: Y - Yes</b>
   */
  isCheckIfHeaderContainsLocation (model) {
  }

  /**
   * <b>A01: create finding</b><br>
   * <br>
   * The enum generation has been triggered in project.ini by:<br>
   * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=check if localhost, create finding; Symbol; Title<br>
   * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
   */
  doCreateFinding (/* CreateFinding */ arg, model) {
  }

  /**
   * <b>A02: execute http request</b><br>
   * <br>
   * The enum generation has been triggered in project.ini by:<br>
   * - <b>IDE.JavaScript.InterfaceEnum.20</b>: IncludeTagsTitle=execute http request; Symbol<br>
   * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
   */
  doExecuteHttpRequest (/* ExecuteHttpRequest */ arg, model) {
  }
}

/**
 * <b>B03: check if localhost</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=check if localhost, create finding; Symbol; Title<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class CheckIfLocalhost {
  #symbol
  #title

  constructor (symbol, title) {
    this.#symbol = symbol
    this.#title = title
  }

  getSymbol () {
    return this.#symbol
  }

  getTitle () {
    return this.#title
  }
}

/**
 * <b>A01: create finding</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=check if localhost, create finding; Symbol; Title<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class CreateFinding {
  #symbol
  #title

  constructor (symbol, title) {
    this.#symbol = symbol
    this.#title = title
  }

  getSymbol () {
    return this.#symbol
  }

  getTitle () {
    return this.#title
  }
}

/**
 * <b>A02: execute http request</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.20</b>: IncludeTagsTitle=execute http request; Symbol<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class ExecuteHttpRequest {
  #symbol

  constructor (symbol) {
    this.#symbol = symbol
  }

  getSymbol () {
    return this.#symbol
  }
}

// Epilog Standard ---->
// profile LFET.Java.Epilog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240629a) build in default

/**
 * <b>B03: check if localhost</b><br>
 * <br>
 * <b>B03/01: localhost - \/\/localhost</b>
 */
const CHECK_IF_LOCALHOST_LOCALHOST = new CheckIfLocalhost('localhost', '\\/\\/localhost')

/**
 * <b>B03: check if localhost</b><br>
 * <br>
 * <b>B03/02: 127.0.0.x - \/\/127\.0\.0\.[0-9]*</b>
 */
const CHECK_IF_LOCALHOST_12700_X = new CheckIfLocalhost('127.0.0.x', '\\/\\/127\\.0\\.0\\.[0-9]*')

const CHECK_IF_LOCALHOST = [
  CHECK_IF_LOCALHOST_LOCALHOST,
  CHECK_IF_LOCALHOST_12700_X
]

/**
 * <b>A01: create finding</b><br>
 * <br>
 * <b>A01/01: REDIRECT - Warning: href={href} returned statuscode {statusCode}, new location: {locationHeader}</b>
 */
const CREATE_FINDING_REDIRECT = new CreateFinding('REDIRECT', 'Warning: href={href} returned statuscode {statusCode}, new location: {locationHeader}')

/**
 * <b>A01: create finding</b><br>
 * <br>
 * <b>A01/02: NUMERIC_IP - Warning: numerical urls (ip address) indicates suspicious environment dependency: href={href}</b>
 */
const CREATE_FINDING_NUMERIC_IP = new CreateFinding('NUMERIC_IP', 'Warning: numerical urls (ip address) indicates suspicious environment dependency: href={href}')

/**
 * <b>A01: create finding</b><br>
 * <br>
 * <b>A01/03: LOCALHOST - Warning: localhost urls indicates suspicious environment dependency: href={href}</b>
 */
const CREATE_FINDING_LOCALHOST = new CreateFinding('LOCALHOST', 'Warning: localhost urls indicates suspicious environment dependency: href={href}')

/**
 * <b>A01: create finding</b><br>
 * <br>
 * <b>A01/04: WARN - Warning: href={href} returned statuscode {statusCode}</b>
 */
const CREATE_FINDING_WARN = new CreateFinding('WARN', 'Warning: href={href} returned statuscode {statusCode}')

/**
 * <b>A01: create finding</b><br>
 * <br>
 * <b>A01/05: ERROR - Error: href={href} returned statuscode {statusCode}</b>
 */
const CREATE_FINDING_ERROR = new CreateFinding('ERROR', 'Error: href={href} returned statuscode {statusCode}')

/**
 * <b>A01: create finding</b><br>
 * <br>
 * <b>A01/06: UNKNOWN - Error: Unknown or unclassified response code: href={href} returned statuscode {statusCode}</b>
 */
const CREATE_FINDING_UNKNOWN = new CreateFinding('UNKNOWN', 'Error: Unknown or unclassified response code: href={href} returned statuscode {statusCode}')

const CREATE_FINDING = [
  CREATE_FINDING_REDIRECT,
  CREATE_FINDING_NUMERIC_IP,
  CREATE_FINDING_LOCALHOST,
  CREATE_FINDING_WARN,
  CREATE_FINDING_ERROR,
  CREATE_FINDING_UNKNOWN
]

/**
 * <b>A02: execute http request</b><br>
 * <br>
 * <b>A02/01: HEAD - head request</b>
 */
const EXECUTE_HTTP_REQUEST_HEAD = new ExecuteHttpRequest('HEAD')

/**
 * <b>A02: execute http request</b><br>
 * <br>
 * <b>A02/02: GET - get request</b>
 */
const EXECUTE_HTTP_REQUEST_GET = new ExecuteHttpRequest('GET')

const EXECUTE_HTTP_REQUEST = [
  EXECUTE_HTTP_REQUEST_HEAD,
  EXECUTE_HTTP_REQUEST_GET
]

module.exports = {

  DecisionTableLogic: IBrokenHttpLinksChecker,

  CHECK_IF_LOCALHOST,
  CHECK_IF_LOCALHOST_LOCALHOST,
  CHECK_IF_LOCALHOST_12700_X,

  CREATE_FINDING,
  CREATE_FINDING_REDIRECT,
  CREATE_FINDING_NUMERIC_IP,
  CREATE_FINDING_LOCALHOST,
  CREATE_FINDING_WARN,
  CREATE_FINDING_ERROR,
  CREATE_FINDING_UNKNOWN,

  EXECUTE_HTTP_REQUEST,
  EXECUTE_HTTP_REQUEST_HEAD,
  EXECUTE_HTTP_REQUEST_GET
}

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240629a), https://www.lohrfink.de/lfet
