// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240526a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/BrokenHttpLinksChecker.lfet"
// 02.06.2024 23:15
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240526a) build in default

class IBrokenHttpLinksChecker {
  // Prolog Standard <----

  /**
   * <b>B02: ignore localhost check</b><br>
   * <br>
   * <b>B02/01: Y - Yes</b>
   */
  isIgnoreLocalhostCheck (model) {
  }

  /**
   * <b>B03: check if localhost</b><br>
   * <br>
   * The enum generation has been triggered in project.ini by:<br>
   * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=check if localhost; Symbol; Title<br>
   * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
   */
  isCheckIfLocalhost (/* CheckIfLocalhost */ arg, model) {
  }

  /**
   * <b>B04: ignore ip address check</b><br>
   * <br>
   * <b>B04/01: Y - Yes</b>
   */
  isIgnoreIpAddressCheck (model) {
  }

  /**
   * <b>B05: check if ip address</b><br>
   * <br>
   * <b>B05/01: Y - Yes</b>
   */
  isCheckIfIpAddress (model) {
  }

  /**
   * <b>B06: check http status code in configured success range</b><br>
   * <br>
   * <b>B06/01: SUCCESS - configured success status code range</b>
   */
  isCheckHttpStatusCodeInConfiguredSuccessRange_SUCCESS (model) {
  }

  /**
   * <b>B07: check http status code in configured warning range</b><br>
   * <br>
   * <b>B07/01: WARN - configured warn status code range</b>
   */
  isCheckHttpStatusCodeInConfiguredWarningRange_WARN (model) {
  }

  /**
   * <b>B08: check http status code in configured error range</b><br>
   * <br>
   * <b>B08/01: ERROR - configured error status code range</b>
   */
  isCheckHttpStatusCodeInConfiguredErrorRange_ERROR (model) {
  }

  /**
   * <b>B09: check http status code in redirect range</b><br>
   * <br>
   * The enum generation has been triggered in project.ini by:<br>
   * - <b>IDE.JavaScript.InterfaceEnum.30</b>: IncludeTagsTitle=check http status code in redirect range; Title=Interval<br>
   * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
   */
  isCheckHttpStatusCodeInRedirectRange (/* CheckHttpStatusCodeInRedirectRange */ arg, model) {
  }

  /**
   * <b>B10: check if header contains location</b><br>
   * <br>
   * <b>B10/01: Y - Yes</b>
   */
  isCheckIfHeaderContainsLocation (model) {
  }

  /**
   * <b>A01: create finding</b><br>
   * <br>
   * <b>A01/01: REDIRECT - create a finding with information about redirect location</b>
   */
  doCreateFinding_REDIRECT (model) {
  }

  /**
   * <b>A01: create finding</b><br>
   * <br>
   * <b>A01/02: NUMERIC_IP - </b>
   */
  doCreateFinding_NUMERIC_IP (model) {
  }

  /**
   * <b>A01: create finding</b><br>
   * <br>
   * <b>A01/03: LOCALHOST - </b>
   */
  doCreateFinding_LOCALHOST (model) {
  }

  /**
   * <b>A02: execute http request</b><br>
   * <br>
   * The enum generation has been triggered in project.ini by:<br>
   * - <b>IDE.JavaScript.InterfaceEnum.20</b>: IncludeTagsTitle=execute http request; Symbol<br>
   * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
   */
  doExecuteHttpRequest (/* ExecuteHttpRequest */ arg, model) {
  }
}

/**
 * <b>B03: check if localhost</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=check if localhost; Symbol; Title<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class CheckIfLocalhost {
  #symbol
  #title

  constructor (symbol, title) {
    this.#symbol = symbol
    this.#title = title
  }

  getSymbol () {
    return this.#symbol
  }

  getTitle () {
    return this.#title
  }
}

/**
 * <b>B09: check http status code in redirect range</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.30</b>: IncludeTagsTitle=check http status code in redirect range; Title=Interval<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class CheckHttpStatusCodeInRedirectRange {
  #title
  #titleMin
  #titleMax

  constructor (title, titleMin, titleMax) {
    this.#title = title
    this.#titleMin = titleMin
    this.#titleMax = titleMax
  }

  getTitle () {
    return this.#title
  }

  getTitleMin () {
    return this.#titleMin
  }

  getTitleMax () {
    return this.#titleMax
  }

  isInTitleInterval (arg) {
    return this.#titleMin <= arg && arg <= this.#titleMax
  }
}

/**
 * <b>A02: execute http request</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.20</b>: IncludeTagsTitle=execute http request; Symbol<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class ExecuteHttpRequest {
  #symbol

  constructor (symbol) {
    this.#symbol = symbol
  }

  getSymbol () {
    return this.#symbol
  }
}

// Epilog Standard ---->
// profile LFET.Java.Epilog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240526a) build in default

/**
 * <b>B03: check if localhost</b><br>
 * <br>
 * <b>B03/01: localhost - \/\/localhost</b>
 */
const CHECK_IF_LOCALHOST_LOCALHOST = new CheckIfLocalhost('localhost', '\\/\\/localhost')

/**
 * <b>B03: check if localhost</b><br>
 * <br>
 * <b>B03/02: 127.0.0.x - \/\/127\.0\.0\.[0-9]*</b>
 */
const CHECK_IF_LOCALHOST_12700_X = new CheckIfLocalhost('127.0.0.x', '\\/\\/127\\.0\\.0\\.[0-9]*')

const CHECK_IF_LOCALHOST = [
  CHECK_IF_LOCALHOST_LOCALHOST,
  CHECK_IF_LOCALHOST_12700_X
]

/**
 * <b>B09: check http status code in redirect range</b><br>
 * <br>
 * <b>B09/01: 30x - [301:308]</b>
 */
const CHECK_HTTP_STATUS_CODE_IN_REDIRECT_RANGE_30_X = new CheckHttpStatusCodeInRedirectRange('[301:308]', 301, 308)

const CHECK_HTTP_STATUS_CODE_IN_REDIRECT_RANGE = [
  CHECK_HTTP_STATUS_CODE_IN_REDIRECT_RANGE_30_X
]

/**
 * <b>A02: execute http request</b><br>
 * <br>
 * <b>A02/01: HEAD - head request</b>
 */
const EXECUTE_HTTP_REQUEST_HEAD = new ExecuteHttpRequest('HEAD')

/**
 * <b>A02: execute http request</b><br>
 * <br>
 * <b>A02/02: GET - get request</b>
 */
const EXECUTE_HTTP_REQUEST_GET = new ExecuteHttpRequest('GET')

const EXECUTE_HTTP_REQUEST = [
  EXECUTE_HTTP_REQUEST_HEAD,
  EXECUTE_HTTP_REQUEST_GET
]

module.exports = {

  DecisionTableLogic: IBrokenHttpLinksChecker,

  CHECK_IF_LOCALHOST,
  CHECK_IF_LOCALHOST_LOCALHOST,
  CHECK_IF_LOCALHOST_12700_X,

  CHECK_HTTP_STATUS_CODE_IN_REDIRECT_RANGE,
  CHECK_HTTP_STATUS_CODE_IN_REDIRECT_RANGE_30_X,

  EXECUTE_HTTP_REQUEST,
  EXECUTE_HTTP_REQUEST_HEAD,
  EXECUTE_HTTP_REQUEST_GET
}

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240526a), https://www.lohrfink.de/lfet
