// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240216a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 17.02.2024 23:55
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240216a) build in default
const Checker = require('../Checker')

class IMissingImageFilesChecker extends Checker
{

    constructor (config) {super(config)}
// Prolog Standard <----

    /**
     * <b>C02: pageToCheck file defined</b>
     */
    isPageToCheckFileDefined(model) {
    }

    /**
     * <b>C03: one more image tag to check available</b>
     */
    isOneMoreImageTagToCheckAvailable(model) {
    }

    /**
     * <b>A01: set currentDir to ...</b><br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=set currentDir to ...<br>
     * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
     */
    doSetCurrentDirTo(/* SetCurrentDirTo */ arg) {
    }

    /**
     * <b>A02: get all image tags</b>
     */
    doGetAllImageTags(model) {
    }

    /**
     * <b>A03: next image tag</b>
     */
    doNextImageTag(model) {
    }

    doSetRuleGroup(rgNr, rgSymbol, rgTitle, model) {
    }

    doTrace(dtName, version, rules, rule, model) {
    }

    doTraceAfterRule(dtName, version, rules, rule, model) {
    }
}

/**
 * <b>A01: set currentDir to ...</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=set currentDir to ...<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class SetCurrentDirTo
{
}

module.exports = {
    IMissingImageFilesChecker: IMissingImageFilesChecker,
    SetCurrentDirTo_CONF: new SetCurrentDirTo(),
    SetCurrentDirTo_PTC: new SetCurrentDirTo()
}
// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240216a), https://www.lohrfink.de/lfet
