// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240216a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 18.02.2024 22:01
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240216a) build in default

class IMissingImageFilesChecker
{

// Prolog Standard <----

    /**
     * <b>B01: image src is data uri</b>
     */
    isImageSrcIsDataUri(model) {
    }

    /**
     * <b>B02: image src is remote uri</b>
     */
    isImageSrcIsRemoteUri(model) {
    }

    /**
     * <b>B03: image src contains data</b>
     */
    isImageSrcContainsData(model) {
    }

    /**
     * <b>B04: local image file exists</b>
     */
    isLocalImageFileExists(model) {
    }

    /**
     * <b>A01: create finding</b>
     */
    doCreateFinding(model) {
    }

    /**
     * <b>A02: inc number of checks</b><br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=inc number of checks; CA=Text<br>
     * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
     */
    doIncNumberOfChecks(/* int */ arg, model) {
    }

    doTrace(dtName, version, rules, rule, model) {
    }

    doTraceAfterRule(dtName, version, rules, rule, model) {
    }
}

module.exports = IMissingImageFilesChecker
// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240216a), https://www.lohrfink.de/lfet
