// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240218a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 19.02.2024 22:16
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (240218a) build in default

class IMissingImageFilesChecker
{
// Prolog Standard <----

    /**
     * <b>B01: image src is data uri</b>
     */
    isImageSrcIsDataUri(model) {
    }

    /**
     * <b>B02: image src is remote uri</b>
     */
    isImageSrcIsRemoteUri(model) {
    }

    /**
     * <b>B03: image src contains data</b>
     */
    isImageSrcContainsData(model) {
    }

    /**
     * <b>B04: local image file exists</b>
     */
    isLocalImageFileExists(model) {
    }

    /**
     * <b>A01: create finding</b><br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>IDE.JavaScript.InterfaceEnum.20</b>: IncludeTagsTitle=create finding; Symbol; CA=Text; Title<br>
     * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
     */
    doCreateFinding(/* CreateFinding */ arg, model) {
    }

    /**
     * <b>A02: inc number of checks</b><br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=inc number of checks; Symbol=Integer<br>
     * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
     */
    doIncNumberOfChecks(/* IncNumberOfChecks */ arg, model) {
    }
}

/**
 * <b>A01: create finding</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.20</b>: IncludeTagsTitle=create finding; Symbol; Title<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class CreateFinding
{
    constructor(symbol, title)
    {
        this.symbol = symbol;
        this.title = title;
    }

    getSymbol()
    {
        return this.symbol;
    }

    getTitle()
    {
        return this.title;
    }
}

/**
 * <b>A02: inc number of checks</b><br>
 * <br>
 * The enum generation has been triggered in project.ini by:<br>
 * - <b>IDE.JavaScript.InterfaceEnum.10</b>: IncludeTagsTitle=inc number of checks; Symbol=Integer<br>
 * - <b>ide.JavaScript.InterfaceEnum.default</b>: MethodName=Prefix; EnumValueName=Symbol, UpperCase
 */
class IncNumberOfChecks
{
    constructor(symbol, symbolInt)
    {
        this.symbol = symbol;
        this.symbolInt = symbolInt;
    }

    getSymbol()
    {
        return this.symbol;
    }

    getSymbolInteger()
    {
        return this.symbolInt;
    }
}



    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.3.0 (240218a) build in default

module.exports = {
    DecisionTableLogic: IMissingImageFilesChecker,
    CreateFinding_DATA: new CreateFinding("DATA", "data-uri image missing"),
    CreateFinding_FILE: new CreateFinding("FILE", "image '$relativePathToImageFile' missing"),
    IncNumberOfChecks_1: new IncNumberOfChecks("+1", 1),
    IncNumberOfChecks_0: new IncNumberOfChecks("0", 0)
}

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240218a), https://www.lohrfink.de/lfet
