// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240214a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 17.02.2024 00:37
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (240214a) build in default

// cav = condition and action values
import * as cav from "./IMissingImageFilesChecker.js"

export class MissingImageFilesChecker {
    execute(/* IMissingImageFilesChecker */ iFace) {

    // Prolog Standard <----

        if ( iFace.isTitelFuerBedingung1() ) {
            // Rule R01 ---->

            iFace.doTrace("MissingImageFilesChecker", "20240217.003727", 2, 1);

            iFace.doTitelFuerAktion1();

            // Rule R01 <----
        } else {
            // Rule R02 ---->

            iFace.doTrace("MissingImageFilesChecker", "20240217.003727", 2, 2);

            iFace.doTitelFuerAktion2();

            // Rule R02 <----
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (240214a) build in default

    }

}

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240214a), https://www.lohrfink.de/lfet
