// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240526a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 02.06.2024 01:54
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (240526a) build in default

// cav = condition and action values
const cav = require('./IMissingImageFilesChecker.js')

class MissingImageFilesCheckerDecisionLogic {
  constructor (/* LoggingFacade */ logger) {
    this.logger = logger
  }

  execute (/* IMissingImageFilesChecker */ iface, model) {
    // Prolog Standard <----

    if (iface.isImageSrcIsDataUri(model)) {
      if (iface.isImageSrcContainsData(model)) {
        // Rule R01 ---->

        this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 1 / 5 - ${JSON.stringify(model)}`)

        iface.doIncNumberOfChecks(cav.INC_NUMBER_OF_CHECKS_1, model) // +1 - one check

        this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 1 / 5 - ${JSON.stringify(model)}`)

        // Rule R01 <----
      } else {
        // Rule R02 ---->

        this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 2 / 5 - ${JSON.stringify(model)}`)

        iface.doCreateFinding(cav.CREATE_FINDING_DATA, model) // DATA - data-uri image missing
        iface.doIncNumberOfChecks(cav.INC_NUMBER_OF_CHECKS_1, model) // +1 - one check

        this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 2 / 5 - ${JSON.stringify(model)}`)

        // Rule R02 <----
      }
    } else {
      if (iface.isImageSrcIsRemoteUri(model)) {
        // Rule R03 ---->

        this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 3 / 5 - ${JSON.stringify(model)}`)

        iface.doIncNumberOfChecks(cav.INC_NUMBER_OF_CHECKS_0, model) // 0 - 0 checks

        this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 3 / 5 - ${JSON.stringify(model)}`)

        // Rule R03 <----
      } else {
        if (iface.isLocalImageFileExists(model)) {
          // Rule R04 ---->

          this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 4 / 5 - ${JSON.stringify(model)}`)

          iface.doIncNumberOfChecks(cav.INC_NUMBER_OF_CHECKS_1, model) // +1 - one check

          this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 4 / 5 - ${JSON.stringify(model)}`)

          // Rule R04 <----
        } else {
          // Rule R05 ---->

          this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 5 / 5 - ${JSON.stringify(model)}`)

          iface.doCreateFinding(cav.CREATE_FINDING_FILE, model) // FILE - image "$relativePathToImageFile" missing
          iface.doIncNumberOfChecks(cav.INC_NUMBER_OF_CHECKS_1, model) // +1 - one check

          this.logger.log(`MissingImageFilesChecker - 20240602.015401 - 5 / 5 - ${JSON.stringify(model)}`)

          // Rule R05 <----
        }
      }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
    // used LF-ET 2.3.0 (240526a) build in default
  }
}

module.exports = MissingImageFilesCheckerDecisionLogic

// Epilog Standard <----

// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240526a), https://www.lohrfink.de/lfet
