// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.3.0 (240216a), https://www.lohrfink.de/lfet
// From decision table
// "../htmlSanityCheck.js/lfet/checker/MissingImageFilesChecker.lfet"
// 18.02.2024 22:01
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (240216a) build in default

// cav = condition and action values

class MissingImageFilesCheckerDecisionLogic {
    execute(/* IMissingImageFilesChecker */ iface, model) {
        // Prolog Standard <----

        if (iface.isImageSrcIsDataUri(model)) {
            if (iface.isImageSrcContainsData(model)) {
                // Rule R01 ---->

                iface.doTrace("MissingImageFilesChecker", "20240218.220113", 5, 1, model)

                iface.doIncNumberOfChecks(1, model) // +1 - one check

                iface.doTraceAfterRule("MissingImageFilesChecker", "20240218.220113", 5, 1, model)

                // Rule R01 <----
            } else {
                // Rule R02 ---->

                iface.doTrace("MissingImageFilesChecker", "20240218.220113", 5, 2, model)

                iface.doCreateFinding(model)
                iface.doIncNumberOfChecks(1, model) // +1 - one check

                iface.doTraceAfterRule("MissingImageFilesChecker", "20240218.220113", 5, 2, model)

                // Rule R02 <----
            }
        } else {
            if (iface.isImageSrcIsRemoteUri(model)) {
                // Rule R03 ---->

                iface.doTrace("MissingImageFilesChecker", "20240218.220113", 5, 3, model)

                iface.doIncNumberOfChecks(0, model) // 0 - 0 checks

                iface.doTraceAfterRule("MissingImageFilesChecker", "20240218.220113", 5, 3, model)

                // Rule R03 <----
            } else {
                if (iface.isLocalImageFileExists(model)) {
                    // Rule R04 ---->

                    iface.doTrace("MissingImageFilesChecker", "20240218.220113", 5, 4, model)

                    iface.doIncNumberOfChecks(1, model) // +1 - one check

                    iface.doTraceAfterRule("MissingImageFilesChecker", "20240218.220113", 5, 4, model)

                    // Rule R04 <----
                } else {
                    // Rule R05 ---->

                    iface.doTrace("MissingImageFilesChecker", "20240218.220113", 5, 5, model)

                    iface.doCreateFinding(model)
                    iface.doIncNumberOfChecks(1, model) // +1 - one check

                    iface.doTraceAfterRule("MissingImageFilesChecker", "20240218.220113", 5, 5, model)

                    // Rule R05 <----
                }
            }
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (240216a) build in default

    }

}

// Epilog Standard <----
module.exports = MissingImageFilesCheckerDecisionLogic
// End of generated JavaScript source code
// Generated by LF-ET 2.3.0 (240216a), https://www.lohrfink.de/lfet
